### ISSUE TITLE
OCP 3.7 cluster deployment is failing while processing "deployOpenshift"

### ISSUE THREAD

**Issue by fasalzaman** [Microsoft/openshift-container-platform#138]
While deploying Openshift cluster -release 3.7, it is failing with the following error message:
Can somebody look in to this issue.
It was deploying succesfully a couple of days back.

error message:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=2\\n[stdout]\\n: u'', u'rc': 0, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': False, u'_raw_params': u\\\"oc get deploymentconfig router --namespace default --config /etc/origin/master/admin.kubeconfig -o jsonpath='{ .status.latestVersion }'\\\", u'removes': None, u'creates': None, u'chdir': None, u'stdin': None}}, 'stdout_lines': [u'1'], u'start': u'2018-11-02 06:42:53.992642', '_ansible_ignore_errors': None, 'failed': False}]) => {\\\"attempts\\\": 1, \\\"changed\\\": true, \\\"cmd\\\": [\\\"oc\\\", \\\"get\\\", \\\"replicationcontroller\\\", \\\"router-1\\\", \\\"--namespace\\\", \\\"default\\\", \\\"--config\\\", \\\"/etc/origin/master/admin.kubeconfig\\\", \\\"-o\\\", \\\"jsonpath={ .metadata.annotations.openshift\\\\\\\\.io/deployment\\\\\\\\.phase }\\\"], \\\"delta\\\": \\\"0:00:00.217747\\\", \\\"end\\\": \\\"2018-11-02 06:42:54.924090\\\", \\\"failed_when_result\\\": true, \\\"item\\\": [{\\\"certificate\\\": {\\\"cafile\\\": \\\"/etc/origin/master/ca.crt\\\", \\\"certfile\\\": \\\"/etc/origin/master/openshift-router.crt\\\", \\\"keyfile\\\": \\\"/etc/origin/master/openshift-router.key\\\"}, \\\"edits\\\": [{\\\"action\\\": \\\"put\\\", \\\"key\\\": \\\"spec.strategy.rollingParams.intervalSeconds\\\", \\\"value\\\": 1}, {\\\"action\\\": \\\"put\\\", \\\"key\\\": \\\"spec.strategy.rollingParams.updatePeriodSeconds\\\", \\\"value\\\": 1}, {\\\"action\\\": \\\"put\\\", \\\"key\\\": \\\"spec.strategy.activeDeadlineSeconds\\\", \\\"value\\\": 21600}], \\\"images\\\": \\\"openshift3/ose-${component}:${version}\\\", \\\"name\\\": \\\"router\\\", \\\"namespace\\\": \\\"default\\\", \\\"ports\\\": [\\\"80:80\\\", \\\"443:443\\\"], \\\"replicas\\\": \\\"1\\\", \\\"selector\\\": \\\"region=infra\\\", \\\"serviceaccount\\\": \\\"router\\\", \\\"stats_port\\\": 1936}, {\\\"_ansible_ignore_errors\\\": null, \\\"_ansible_item_result\\\": true, \\\"_ansible_no_log\\\": false, \\\"_ansible_parsed\\\": true, \\\"changed\\\": true, \\\"cmd\\\": [\\\"oc\\\", \\\"get\\\", \\\"deploymentconfig\\\", \\\"router\\\", \\\"--namespace\\\", \\\"default\\\", \\\"--config\\\", \\\"/etc/origin/master/admin.kubeconfig\\\", \\\"-o\\\", \\\"jsonpath={ .status.latestVersion }\\\"], \\\"delta\\\": \\\"0:00:00.238601\\\", \\\"end\\\": \\\"2018-11-02 06:42:54.231243\\\", \\\"failed\\\": false, \\\"invocation\\\": {\\\"module_args\\\": {\\\"_raw_params\\\": \\\"oc get deploymentconfig router --namespace default --config /etc/origin/master/admin.kubeconfig -o jsonpath='{ .status.latestVersion }'\\\", \\\"_uses_shell\\\": false, \\\"chdir\\\": null, \\\"creates\\\": null, \\\"executable\\\": null, \\\"removes\\\": null, \\\"stdin\\\": null, \\\"warn\\\": true}}, \\\"item\\\": {\\\"certificate\\\": {\\\"cafile\\\": \\\"/etc/origin/master/ca.crt\\\", \\\"certfile\\\": \\\"/etc/origin/master/openshift-router.crt\\\", \\\"keyfile\\\": \\\"/etc/origin/master/openshift-router.key\\\"}, \\\"edits\\\": [{\\\"action\\\": \\\"put\\\", \\\"key\\\": \\\"spec.strategy.rollingParams.intervalSeconds\\\", \\\"value\\\": 1}, {\\\"action\\\": \\\"put\\\", \\\"key\\\": \\\"spec.strategy.rollingParams.updatePeriodSeconds\\\", \\\"value\\\": 1}, {\\\"action\\\": \\\"put\\\", \\\"key\\\": \\\"spec.strategy.activeDeadlineSeconds\\\", \\\"value\\\": 21600}], \\\"images\\\": \\\"openshift3/ose-${component}:${version}\\\", \\\"name\\\": \\\"router\\\", \\\"namespace\\\": \\\"default\\\", \\\"ports\\\": [\\\"80:80\\\", \\\"443:443\\\"], \\\"replicas\\\": \\\"1\\\", \\\"selector\\\": \\\"region=infra\\\", \\\"serviceaccount\\\": \\\"router\\\", \\\"stats_port\\\": 1936}, \\\"rc\\\": 0, \\\"start\\\": \\\"2018-11-02 06:42:53.992642\\\", \\\"stderr\\\": \\\"\\\", \\\"stderr_lines\\\": [], \\\"stdout\\\": \\\"1\\\", \\\"stdout_lines\\\": [\\\"1\\\"]}], \\\"rc\\\": 0, \\\"start\\\": \\\"2018-11-02 06:42:54.706343\\\", \\\"stderr\\\": \\\"\\\", \\\"stderr_lines\\\": [], \\\"stdout\\\": \\\"Failed\\\", \\\"stdout_lines\\\": [\\\"Failed\\\"]}\\n\\nPLAY RECAP *********************************************************************\\nlocalhost : ok=12 changed=0 unreachable=0 failed=0 \\nmycluster-infra-0 : ok=198 changed=67 unreachable=0 failed=0 \\nmycluster-master-0 : ok=548 changed=203 unreachable=0 failed=1 \\nmycluster-node-0 : ok=198 changed=67 unreachable=0 failed=0 \\n\\n\\nINSTALLER STATUS ***************************************************************\\nInitialization : Complete\\nHealth Check : Complete\\netcd Install : Complete\\nMaster Install : Complete\\nMaster Additional Install : Complete\\nNode Install : Complete\\nHosted Install : In Progress\\n\\tThis phase can be restarted by running: playbooks/byo/openshift-cluster/openshift-hosted.yml\\n\\n\\n\\nFailure summary:\\n\\n\\n 1. Hosts: mycluster-master-0\\n Play: Create Hosted Resources - router\\n Task: Poll for OpenShift pod deployment success\\n Message: All items completed\\n\\n[stderr]\\n % Total % Received % Xferd Average Speed Time Time Time Current\\n Dload Upload Total Spent Left Speed\\n\\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\\r100 6 100 6 0 0 1010 0 --:--:-- --:--:-- --:--:-- 1200\\n[DEPRECATION WARNING]: 'include' for playbook includes. You should use \\n'import_playbook' instead. This feature will be removed in version 2.8. \\nDeprecation warnings can be disabled by setting deprecation_warnings=False in \\nansible.cfg.\\n[DEPRECATION WARNING]: 'include' for playbook includes. You should use \\n'import_playbook' instead. This feature will be removed in version 2.8. \\nDeprecation warnings can be disabled by setting deprecation_warnings=False in \\nansible.cfg.\\n[DEPRECATION WARNING]: The use of 'static' for 'include_role' has been \\ndeprecated. Use 'import_role' for static inclusion, or 'include_role' for \\ndynamic inclusion. This feature will be removed in a future release. \\nDeprecation warnings can be disabled by setting deprecation_warnings=False in \\nansible.cfg.\\n[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use \\n'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.\\n This feature will be removed in a future release. Deprecation warnings can be \\ndisabled by setting deprecation_warnings=False in ansible.cfg.\\n[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is\\n discouraged. The module documentation details page may explain more about this\\n rationale.. This feature will be removed in a future release. Deprecation \\nwarnings can be disabled by setting deprecation_warnings=False in ansible.cfg.\\n[DEPRECATION WARNING]: The use of 'static' has been deprecated. Use \\n'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion. \\nThis feature will be removed in a future release. Deprecation warnings can be \\ndisabled by setting deprecation_warnings=False in ansible.cfg.\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_all_hosts\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config\\n [WARNING]: Consider using yum, dnf or zypper module rather than running rpm\\n [WARNING]: Consider using get_url or uri module rather than running curl\\n [WARNING]: Could not match supplied host pattern, ignoring:\\noo_containerized_master_nodes\\n [WARNING]: Could not match supplied host pattern, ignoring:\\noo_nodes_use_flannel\\n [WARNING]: Could not match supplied host pattern, ignoring:\\noo_nodes_use_calico\\n [WARNING]: Could not match supplied host pattern, ignoring:\\noo_nodes_use_contiv\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_nodes_use_kuryr\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_nodes_use_nuage\\n [WARNING]: Could not match supplied host pattern, ignoring: glusterfs\\n [WARNING]: Could not match supplied host pattern, ignoring: glusterfs_registry\\n [WARNING]: Module did not set no_log for stats_password\\n [WARNING]: Module did not set no_log for external_host_password\\n [WARNING]: Could not create retry file '/usr/share/ansible/openshift-\\nansible/playbooks/byo/config.retry'. [Errno 13] Permission denied:\\nu'/usr/share/ansible/openshift-ansible/playbooks/byo/config.retry'\\n\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by MeeraRepo** [comment]
Hi,
While deploying Openshift Container Platform-3.10, 

We are facing an error as" “VM has reported a failure when processing extension deployOpenShift”. 

Can somebody look into this issue. it would be helpful.  Thanks in advance..!!

Please find the below detailed information about parameters and error.

Parameters we used:
Master VM size: Standard_E2s_v3
Node VM size : Standard_DS4_v2
Infra VM size : Standard_DS4_v2
CNS VM size : Standard_E4s_v3
masterInstanceCount : 3
nodeInstanceCount: 3
InfraInstanceCount: 3
CNSInstanceCount : 3 ( CNS is Enabled ) 
dataDiskSize : 128 GB
enableAzure: True
Enable Metrics: True
Enable Logging : True


Error we received while deploying through ARM Template:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"DeploymentFailed\",\r\n \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n \"details\": [\r\n {\r\n \"code\": \"Conflict\",\r\n \"message\": \"{\\r\\n \\\"status\\\": \\\"Failed\\\",\\r\\n \\\"error\\\": {\\r\\n \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"VMExtensionProvisioningError\\\",\\r\\n \\\"message\\\": \\\"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\\\\\"Enable failed: failed to execute command: command terminated with exit status=2\\\\n[stdout]\\\\nvice-broker/key.pem -CAcreateserial -out /etc/origin/ansible-service-broker/client.pem -days 1024'})\\\\n\\\\nTASK [ansible_service_broker : set_fact] ***************************************\\\\nok: [ocpcluster-master-0]\\\\n\\\\nTASK [ansible_service_broker : Read in certs for etcd] *************************\\\\nok: [ocpcluster-master-0] => (item=cert.pem)\\\\nok: [ocpcluster-master-0] => (item=client.pem)\\\\nok: [ocpcluster-master-0] => (item=client.key)\\\\n\\\\nTASK [ansible_service_broker : set_fact] ***************************************\\\\nok: [ocpcluster-master-0]\\\\n\\\\nTASK [ansible_service_broker : create openshift-ansible-service-broker project] ***\\\\nchanged: [ocpcluster-master-0]\\\\n\\\\nTASK [ansible_service_broker : create ansible-service-broker serviceaccount] ***\\\\nchanged: [ocpcluster-master-0]\\\\n\\\\nTASK [ansible_service_broker : create ansible-service-broker client serviceaccount] ***\\\\nchanged: [ocpcluster-master-0]\\\\n\\\\nTASK [ansible_service_broker : Create asb-auth cluster role] *******************\\\\nchanged: [ocpcluster-master-0]\\\\n\\\\nTASK [ansible_service_broker : Create asb-access cluster role] *****************\\\\nchanged: [ocpcluster-master-0]\\\\n\\\\nTASK [ansible_service_broker : Bind admin cluster-role to asb serviceaccount] ***\\\\nchanged: [ocpcluster-master-0]\\\\n\\\\nTASK [ansible_service_broker : Bind auth cluster role to asb service account] ***\\\\nchanged: [ocpcluster-master-0]\\\\n\\\\nTASK [ansible_service_broker : Bind asb-access role to asb-client service account] ***\\\\nchanged: [ocpcluster-master-0]\\\\n\\\\nTASK [ansible_service_broker : create asb-client token secret] *****************\\\\nchanged: [ocpcluster-master-0]\\\\n\\\\nTASK [ansible_service_broker : oc_secret] **************************************\\\\nok: [ocpcluster-master-0]\\\\n\\\\nTASK [ansible_service_broker : set_fact] ***************************************\\\\nok: [ocpcluster-master-0]\\\\n\\\\nTASK [ansible_service_broker : Create custom resource definitions for asb] *****\\\\nchanged: [ocpcluster-master-0] => (item=/usr/share/ansible/openshift-ansible/roles/ansible_service_broker/files/bundlebindings.automationbroker.io.yaml)\\\\nchanged: [ocpcluster-master-0] => (item=/usr/share/ansible/openshift-ansible/roles/ansible_service_broker/files/bundleinstances.automationbroker.io.yaml)\\\\nfailed: [ocpcluster-master-0] (item=/usr/share/ansible/openshift-ansible/roles/ansible_service_broker/files/bundles.automationbroker.io.yaml) => {\\\\\\\"changed\\\\\\\": false, \\\\\\\"item\\\\\\\": \\\\\\\"/usr/share/ansible/openshift-ansible/roles/ansible_service_broker/files/bundles.automationbroker.io.yaml\\\\\\\", \\\\\\\"msg\\\\\\\": {\\\\\\\"cmd\\\\\\\": \\\\\\\"/bin/oc create -f /tmp/bundles.automationbroker.io-jKhC5w -n default\\\\\\\", \\\\\\\"results\\\\\\\": {}, \\\\\\\"returncode\\\\\\\": 1, \\\\\\\"stderr\\\\\\\": \\\\\\\"Error from server: error when creating \\\\\\\\\\\\\\\"/tmp/bundles.automationbroker.io-jKhC5w\\\\\\\\\\\\\\\": etcdserver: request timed out\\\\\\\\n\\\\\\\", \\\\\\\"stdout\\\\\\\": \\\\\\\"\\\\\\\"}}\\\\n\\\\nPLAY RECAP *********************************************************************\\\\nlocalhost : ok=12 changed=0 unreachable=0 failed=0 \\\\nocpcluster-cns-0 : ok=0 changed=0 unreachable=0 failed=0 \\\\nocpcluster-cns-1 : ok=0 changed=0 unreachable=0 failed=0 \\\\nocpcluster-cns-2 : ok=0 changed=0 unreachable=0 failed=0 \\\\nocpcluster-infra-0 : ok=0 changed=0 unreachable=0 failed=0 \\\\nocpcluster-infra-1 : ok=0 changed=0 unreachable=0 failed=0 \\\\nocpcluster-infra-2 : ok=0 changed=0 unreachable=0 failed=0 \\\\nocpcluster-master-0 : ok=113 changed=37 unreachable=0 failed=1 \\\\nocpcluster-master-1 : ok=35 changed=1 unreachable=0 failed=0 \\\\nocpcluster-master-2 : ok=35 changed=1 unreachable=0 failed=0 \\\\nocpcluster-node-0 : ok=0 changed=0 unreachable=0 failed=0 \\\\nocpcluster-node-1 : ok=0 changed=0 unreachable=0 failed=0 \\\\nocpcluster-node-2 : ok=0 changed=0 unreachable=0 failed=0 \\\\n\\\\n\\\\nINSTALLER STATUS ***************************************************************\\\\nInitialization : Complete (0:00:52)\\\\nService Catalog Install : In Progress (0:01:34)\\\\n\\\\tThis phase can be restarted by running: playbooks/openshift-service-catalog/config.yml\\\\n\\\\n[stderr]\\\\n % Total % Received % Xferd Average Speed Time Time Time Current\\\\n Dload Upload Total Spent Left Speed\\\\n\\\\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\\\\r100 6 100 6 0 0 1004 0 --:--:-- --:--:-- --:--:-- 1200\\\\nWARNING: The installed extension 'storage-preview' is in preview.\\\\nWARNING: The behavior of this command has been altered by the following extension: storage-preview\\\\n# ocpcluster-cns-0:22 SSH-2.0-OpenSSH_7.4\\\\n# ocpcluster-cns-0:22 SSH-2.0-OpenSSH_7.4\\\\n# ocpcluster-cns-0:22 SSH-2.0-OpenSSH_7.4\\\\nWarning: Permanently added the ECDSA host key for IP address '10.1.0.4' to the list of known hosts.\\\\r\\\\n# ocpcluster-cns-1:22 SSH-2.0-OpenSSH_7.4\\\\n# ocpcluster-cns-1:22 SSH-2.0-OpenSSH_7.4\\\\n# ocpcluster-cns-1:22 SSH-2.0-OpenSSH_7.4\\\\nWarning: Permanently added the ECDSA host key for IP address '10.1.0.5' to the list of known hosts.\\\\r\\\\n# ocpcluster-cns-2:22 SSH-2.0-OpenSSH_7.4\\\\n# ocpcluster-cns-2:22 SSH-2.0-OpenSSH_7.4\\\\n# ocpcluster-cns-2:22 SSH-2.0-OpenSSH_7.4\\\\nWarning: Permanently added the ECDSA host key for IP address '10.1.0.6' to the list of known hosts.\\\\r\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config\\\\n [WARNING]: Consider using the yum, dnf or zypper module rather than running\\\\nrpm. If you need to use command because yum, dnf or zypper is insufficient you\\\\ncan add warn=False to this command task or set command_warnings=False in\\\\nansible.cfg to get rid of this message.\\\\n [WARNING]: Could not match supplied host pattern, ignoring:\\\\noo_hosts_containerized_managed_true\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config\\\\n [WARNING]: Could not match supplied host pattern, ignoring:\\\\noo_exclude_bootstrapped_nodes\\\\n [WARNING]: Consider using the file module with mode rather than running chmod.\\\\nIf you need to use command because file is insufficient you can add warn=False\\\\nto this command task or set command_warnings=False in ansible.cfg to get rid of\\\\nthis message.\\\\n [WARNING]: Consider using the unarchive module rather than running tar. If\\\\nyou need to use command because unarchive is insufficient you can add\\\\nwarn=False to this command task or set command_warnings=False in ansible.cfg to\\\\nget rid of this message.\\\\nWarning: Permanently added 'ocpcluster-master-0,10.1.0.11' (ECDSA) to the list of known hosts.\\\\r\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config\\\\n [WARNING]: Could not create retry file '/usr/share/ansible/openshift-\\\\nansible/playbooks/openshift-service-catalog/config.retry'. [Errno 13]\\\\nPermission denied: u'/usr/share/ansible/openshift-ansible/playbooks/openshift-\\\\nservice-catalog/config.retry'\\\\n\\\\\\\".\\\"\\r\\n }\\r\\n ]\\r\\n }\\r\\n}\"\r\n }\r\n ]\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by MeeraRepo** [comment]
it seems we have modified some parameters and able to deploy the Openshift container platform 3.10 successfully. 

Please see below parameters which we modified to resolve the issue.

Branch: release 3.10
VM size: Defaults
Metrics: false
Logging: false
CNS: true

but can you please provide your inputs on these parameters will be sufficient to run the cluster ..?

and can you please provide any links to enable Metrics and Logging post-deployment..?

**Comment by MeeraRepo** [comment]
Hi 

We have overcome the issue with following changes while deploying.
 
Branch  : release 3.10
VM size : Defaults
Metrics : false
Logging : false
CNS     : true

can someone will help with this please,
As we disabled Metrics and Logging while deployment using the Template, is there any way to create Metrics and Logging after post-deployment..?

**Comment by MeeraRepo** [comment]
Hi 
	
We have tried to deploy metrics and logging after post-deployment and followed the steps which are mentioned in the below URL:
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/virtual-machines/linux/openshift-post-deployment.md 
	
But we are getting the errors as :

TASK [openshift_sanitize_inventory : include_tasks] *********************************************************************************************************
included: /usr/share/ansible/openshift-ansible/roles/openshift_sanitize_inventory/tasks/deprecations.yml for ocpcluster-master-0, ocpcluster-master-1, ocpcluster-master-2

TASK [openshift_sanitize_inventory : Check for usage of deprecated variables] *******************************************************************************
fatal: [ocpcluster-master-0]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
fatal: [ocpcluster-master-1]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
fatal: [ocpcluster-master-2]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
        to retry, use: --limit @/usr/share/ansible/openshift-ansible/playbooks/openshift-logging/config.retry

PLAY RECAP **************************************************************************************************************************************************
localhost                  : ok=12   changed=0    unreachable=0    failed=0
ocpcluster-master-0        : ok=4    changed=0    unreachable=0    failed=1
ocpcluster-master-1        : ok=3    changed=0    unreachable=0    failed=1
ocpcluster-master-2        : ok=3    changed=0    unreachable=0    failed=1


INSTALLER STATUS ********************************************************************************************************************************************
Initialization  : In Progress (0:00:05)

please help us with this...Thanks in advance..!!

**Comment by haroldwongms** [comment]
Give me a few days to look into this.

**Comment by MeeraRepo** [comment]
Hi 

We have fixed the issue by doing the following changes:

Step 1 :  In file /usr/share/ansible/openshift-ansible/roles/openshift_sanitize_inventory/tasks/deprecations.yml 
   
          (no_log: true ) is changed to false
		  no_log: false
		  
Step 2 : Again we have run the ansible-playbook 

         Now we are able to see the error details ( as "{{ }}" is not removed when we passed the variables in inventory file)
		 
		 We have removed "{{ }}"  in inventary ( /etc/ansible/hosts ) file.
		 
Step 3 : After doing that we have successfully executed the ansible-playbook command.

Thank You.

**Comment by MeeraRepo** [comment]
@haroldwongms We haven't changed anything in the deployOpenShift.sh file.  And used the ARM template as it is, but while deploying we disabled the Metrics and Logging.
Post-deployment we have tried to install Metrics and Logging. and we have done the above changes in the file `/etc/ansible/hosts`  on Bastion VM.

**Comment by haroldwongms** [comment]
This should be fixed for 3.10 and 3.11.  No longer maintaining releases older than 3.10.
