### ISSUE TITLE
Private masterClusterType role-out fails

### ISSUE THREAD

**Issue by Borrelworst** [Microsoft/openshift-container-platform#154]
**Describe the bug**
When choosing masterClusterType = Private, the deployment fails. 

**To Reproduce**
1. Set the masterClusterType Private
2. Deploy a cluster with minimal settings (no metrics, no logging, no cns), 1 master, 1 infra, 1 node (I have tried with 3 masters, 3 infra and 3 nodes as well, same issue)
3. Wait for the deployment to fail.
4. See the error

**Expected behavior**
I expect that this would result in a cluster with a internal master loadbalancer. When choosing public everyting works fine. 

**stdout**
changed: [ose11vip-master-0]
TASK [ansible_service_broker : create route for dashboard-redirector service] ***
TASK [ansible_service_broker : Set Ansible Service Broker deployment config] ***
changed: [ose11vip-master-0]
TASK [ansible_service_broker : set auth name and type facts if needed] *********
TASK [ansible_service_broker : Create config map for ansible-service-broker] ***
changed: [ose11vip-master-0]
TASK [ansible_service_broker : oc_secret] **************************************
TASK [ansible_service_broker : Create the Broker resource in the catalog] ******
changed: [ose11vip-master-0]
TASK [ansible_service_broker : include_tasks] **********************************
TASK [template_service_broker : include_tasks] *********************************
included: /usr/share/ansible/openshift-ansible/roles/template_service_broker/tasks/install.yml for ose11vip-master-0
TASK [template_service_broker : include_tasks] *********************************
included: /usr/share/ansible/openshift-ansible/roles/template_service_broker/tasks/deploy.yml for ose11vip-master-0
TASK [template_service_broker : oc_project] ************************************
changed: [ose11vip-master-0]
TASK [template_service_broker : command] ***************************************
ok: [ose11vip-master-0]
TASK [template_service_broker : Copy admin client config] **********************
ok: [ose11vip-master-0]
TASK [template_service_broker : copy] ******************************************
changed: [ose11vip-master-0] => (item=apiserver-template.yaml)
changed: [ose11vip-master-0] => (item=rbac-template.yaml)
changed: [ose11vip-master-0] => (item=template-service-broker-registration.yaml)
changed: [ose11vip-master-0] => (item=apiserver-config.yaml)
TASK [template_service_broker : yedit] *****************************************
ok: [ose11vip-master-0]
TASK [template_service_broker : slurp] *****************************************
ok: [ose11vip-master-0]
TASK [template_service_broker : Apply template file] ***************************
changed: [ose11vip-master-0]
TASK [template_service_broker : Reconcile with RBAC file] **********************
changed: [ose11vip-master-0]
TASK [template_service_broker : Verify that TSB is running] ********************
FAILED - RETRYING: Verify that TSB is running (60 retries left).
FAILED - RETRYING: Verify that TSB is running (59 retries left).
ok: [ose11vip-master-0]
TASK [template_service_broker : slurp] *****************************************
ok: [ose11vip-master-0]
TASK [template_service_broker : Register TSB with broker] **********************
changed: [ose11vip-master-0]
TASK [template_service_broker : file] ******************************************
ok: [ose11vip-master-0]
TASK [template_service_broker : include_tasks] *********************************
PLAY [Service Catalog Install Checkpoint End] **********************************
TASK [Set Service Catalog install 'Complete'] **********************************
ok: [ose11vip-master-0]
PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0   
ose11vip-infra-0           : ok=0    changed=0    unreachable=0    failed=0   
ose11vip-master-0          : ok=131  changed=49   unreachable=0    failed=0   
ose11vip-node-0            : ok=0    changed=0    unreachable=0    failed=0   
INSTALLER STATUS ***************************************************************
Initialization           : Complete (0:00:41)
Service Catalog Install  : Complete (0:04:00)
Now using project "osba" on server "https://ose11vip-master-0:443".
You can add applications to this project with the 'new-app' command. For example, try:
    oc new-app centos/ruby-25-centos7~https://github.com/sclorg/ruby-ex.git
to build a new example application in Ruby.
secret/osba-redis created
secret/osba-open-service-broker-azure-auth created
secret/osba-open-service-broker-azure created
service/osba-redis created
service/osba-open-service-broker-azure created
persistentvolumeclaim/osba-redis-pv-claim created
deployment.extensions/osba-redis created
deployment.extensions/osba-open-service-broker-azure created
clusterservicebroker.servicecatalog.k8s.io/osba created
Thu Feb 14 15:41:56 UTC 2019  - Configure cluster for private masters

**stderr**
Warning: Permanently added 'ose11vip-master-0,10.1.0.5' (ECDSA) to the list of known hosts.
[WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config
[WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config
ERROR! vars file vars.yaml was not found on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option

**Template Information (please complete the following information):**
 - OS: Redhat (standard from template, latest installs RHEL 7.5
 - Branch: Master

**Additional context**
This problem is here already from start. However it has not been solved yet in the role-out of 3.11.

**Comment by Borrelworst** [comment]
Additional information: It fails when running this playbook:

~/openshift-container-platform-playbooks/activate-private-lb.31x.yaml

In this playbook a var file is mentioned:

- hosts: masters
  become: yes
  vars_files:
  - vars.yaml

And this file does not exist: Not on the bastion, and also not on the master.

**Comment by haroldwongms** [comment]
It seems I accidentally deleted the code from the deployment script that creates the vars.yaml file.  I will update that next week.

**Comment by haroldwongms** [comment]
Sorry for the delay.  I have been working on making a major update to the templates and scripts.  I have already incorporated the fixes into the latest version of the templates and have opened a PR with a major revision.  Once this gets reviewed and we merge, all should be good.

**Comment by haroldwongms** [comment]
Fixes now merged into master. Please try again and let me know if you still have issues.

**Comment by wallenc** [comment]
I'm using the most recent templates and I'm still seeing this exact issue:

stdout:

TASK [Set Service Catalog install 'Complete'] **********************************
ok: [ocpclus-master01]

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0
ocpclus-infra01            : ok=0    changed=0    unreachable=0    failed=0
ocpclus-infra02            : ok=0    changed=0    unreachable=0    failed=0
ocpclus-infra03            : ok=0    changed=0    unreachable=0    failed=0
ocpclus-master01           : ok=127  changed=49   unreachable=0    failed=0
ocpclus-master02           : ok=29   changed=1    unreachable=0    failed=0
ocpclus-master03           : ok=29   changed=1    unreachable=0    failed=0
ocpclus-node01             : ok=0    changed=0    unreachable=0    failed=0
ocpclus-node02             : ok=0    changed=0    unreachable=0    failed=0
ocpclus-node03             : ok=0    changed=0    unreachable=0    failed=0


INSTALLER STATUS ***************************************************************
Initialization           : Complete (0:00:49)
Service Catalog Install  : Complete (0:03:26)
Wed Mar 20 02:01:22 UTC 2019  - Configure cluster for private masters

stderr: 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0   1552      0 --:--:-- --:--:-- --:--:--  1444
 [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config
 [WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config
 [WARNING]: Consider using the yum, dnf or zypper module rather than running
rpm.  If you need to use command because yum, dnf or zypper is insufficient you
can add warn=False to this command task or set command_warnings=False in
ansible.cfg to get rid of this message.
 [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config
 [WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config
 [WARNING]: Module remote_tmp /root/.ansible/tmp did not exist and was created
with a mode of 0700, this may cause issues when running as another user. To
avoid this, create the remote_tmp dir with the correct permissions manually
 [WARNING]: Consider using the unarchive module rather than running tar.  If
you need to use command because unarchive is insufficient you can add
warn=False to this command task or set command_warnings=False in ansible.cfg to
get rid of this message.
 [WARNING]: Could not match supplied host pattern, ignoring:
oo_nodes_use_calico
 [WARNING]: Could not match supplied host pattern, ignoring:
oo_glusterfs_to_config
 [WARNING]: Could not match supplied host pattern, ignoring:
oo_elasticsearch_nodes
Warning: Permanently added 'ocpclus-master01,10.2.0.12' (ECDSA) to the list of known hosts.
 [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config
 [WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config
ERROR! vars file vars.yaml was not found on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option

**Comment by haroldwongms** [comment]
Thank you.  I will look into the script.

**Comment by haroldwongms** [comment]
https://github.com/Microsoft/openshift-container-platform/pull/168 provided a fix for this.
